# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 12:03
from __future__ import unicode_literals


from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webmarks_bookmarks', '0011_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbookmark',
            name='uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
