# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Node')),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(default=None, max_length=2000, null=True)),
                ('description', models.TextField(blank=True)),
                ('rate', models.IntegerField(default=0)),
                ('favorite', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('V', 'Valid'), ('T', 'Trash')], default='D', max_length=1)),
                ('archive_id', models.UUIDField(null=True)),
                ('archived_dt', models.DateTimeField(null=True)),
            ],
            bases=('base.node',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=False)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
