# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255)),
                ('url', models.SlugField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField(blank=True, db_column='data')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Node')),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(default=None, max_length=2000, null=True)),
                ('description', models.TextField(blank=True)),
                ('rate', models.IntegerField(default=0)),
                ('favorite', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('V', 'Valid'), ('T', 'Trash')], default='D', max_length=1)),
                ('archive_id', models.IntegerField(null=True)),
                ('archived_dt', models.DateTimeField(null=True)),
            ],
            bases=('base.node',),
        ),
        migrations.CreateModel(
            name='HistoricalBookmark',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('updated_dt', models.DateTimeField(blank=True, editable=False)),
                ('created_dt', models.DateTimeField(blank=True, editable=False)),
                ('kind', models.CharField(choices=[('NOTE', 'Note'), ('TODO', 'Todo'), ('MAIL', 'Mail'), ('LINK', 'Link'), ('FLDR', 'Folder')], default='NOTE', max_length=10)),
                ('indexed_dt', models.DateTimeField(null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('public', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(default=None, max_length=2000, null=True)),
                ('description', models.TextField(blank=True)),
                ('rate', models.IntegerField(default=0)),
                ('favorite', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('V', 'Valid'), ('T', 'Trash')], default='D', max_length=1)),
                ('archive_id', models.IntegerField(null=True)),
                ('archived_dt', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bookmark',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=False)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('user_cre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_user_cre', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_user_upd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Node')),
                ('schedule_dt', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('base.node',),
        ),
        migrations.AddField(
            model_name='historicalbookmark',
            name='node_ptr',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.Node'),
        ),
        migrations.AddField(
            model_name='historicalbookmark',
            name='user_cre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbookmark',
            name='user_upd',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='bookmarks.Tag'),
        ),
        migrations.AddField(
            model_name='archive',
            name='bookmark',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='archive_archives', to='bookmarks.Bookmark'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'user_cre')]),
        ),
    ]
