# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='bookmark',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.RemoveField(
            model_name='mediaattachement',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='model',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='search',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='search',
            name='user_cre',
        ),
        migrations.RemoveField(
            model_name='search',
            name='user_upd',
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.DeleteModel(
            name='MediaAttachement',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
