# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmarks_bookmarks', '0004_auto_20170722_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbookmark',
            name='indexed_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='indexed_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
