# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webmarks_bookmarks', '0005_auto_20170730_1403'),
    ]

    operations = [
       
    ]
