# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmarks_bookmarks', '0006_auto_20170730_1428'),
    ]

    operations = [
       
    ]
