# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webmarks_bookmarks', '0007_auto_20170730_1431'),
    ]

    operations = [

    ]
