# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 12:10
from __future__ import unicode_literals

from django.db import migrations


import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('webmarks_bookmarks', 'node')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webmarks_bookmarks', '0010_add_uuid_field'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be
        # reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
