# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mynotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_cre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='note_user_cre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='user_upd',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='note_user_upd', to=settings.AUTH_USER_MODEL),
        ),
    ]
