# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0002_auto_20161017_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user_upd',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='note_user_upd', to=settings.AUTH_USER_MODEL),
        ),
    ]
