# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-22 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0006_auto_20161020_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.CharField(null=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='notes', to='mynotes.Tag'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
