# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0007_auto_20161022_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='url',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
