# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0008_auto_20161022_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typenote',
            name='code',
            field=models.CharField(choices=[('N', 'Note')], db_index=True, default='D', max_length=64, verbose_name='code'),
        ),
    ]
