# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-22 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mynotes', '0010_auto_20161022_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNote',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('updated_dt', models.DateTimeField(blank=True, editable=False)),
                ('created_dt', models.DateTimeField(blank=True, editable=False)),
                ('type', models.CharField(choices=[('NOTE', 'Note')], default='NOTE', max_length=10)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('V', 'Valid')], default='D', max_length=1)),
                ('public', models.BooleanField(default=False)),
                ('url', models.CharField(default=None, max_length=2000, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_cre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical note',
                'get_latest_by': 'history_date',
            },
        ),
        migrations.AlterField(
            model_name='typenote',
            name='code',
            field=models.CharField(db_index=True, max_length=64, verbose_name='code'),
        ),
    ]
