# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0012_auto_20161023_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='taggs',
            field=models.ManyToManyField(related_name='taggs', to='mynotes.Tag'),
        ),
    ]
