# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0013_note_taggs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalnote',
            old_name='tags',
            new_name='taggs',
        ),
        migrations.RemoveField(
            model_name='note',
            name='taggs',
        ),
        migrations.AddField(
            model_name='note',
            name='taggs',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='mynotes.Tag'),
        ),
    ]
