# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0016_remove_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='mynotes.Tag'),
        ),
    ]
