# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0017_note_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAttachement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='mynotes.Note')),
            ],
        ),
    ]
