# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-06 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0018_noteattachement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tags', models.ManyToManyField(related_name='tags_search', to='mynotes.Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='noteattachement',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynotes.Note'),
        ),
    ]
