# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-06 11:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mynotes', '0019_auto_20161106_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 6, 11, 58, 53, 44268, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 11, 6, 11, 59, 2, 362381, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='user_cre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='search_user_cre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='search',
            name='user_upd',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='search_user_upd', to=settings.AUTH_USER_MODEL),
        ),
    ]
