# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-28 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0020_auto_20161106_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeNote',
            new_name='Model',
        ),
    ]
