# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0021_auto_20161128_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
