# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0023_favorite_fileuploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploader',
            name='type',
            field=models.CharField(choices=[('FAVORITE', 'Favorite')], default='FAVORITE', max_length=10),
            preserve_default=False,
        ),
    ]
