# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-11 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0024_fileuploader_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnote',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
