# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-12 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0025_auto_20170311_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='type',
            field=models.CharField(choices=[('NOTE', 'Note'), ('TODO', 'Todo'), ('MAIL', 'Mail'), ('BOOKMARK', 'BookMark')], default='NOTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('NOTE', 'Note'), ('TODO', 'Todo'), ('MAIL', 'Mail'), ('BOOKMARK', 'BookMark')], default='NOTE', max_length=10),
        ),
    ]
