# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-14 21:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mynotes', '0026_auto_20170312_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 3, 14, 21, 19, 26, 639121, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 14, 21, 19, 41, 886035, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='user_cre',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tag_user_cre', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='user_upd',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tag_user_upd', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='mynotes.Tag'),
        ),
        migrations.AlterField(
            model_name='search',
            name='user_cre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_user_cre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search',
            name='user_upd',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_user_upd', to=settings.AUTH_USER_MODEL),
        ),
    ]
