# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-26 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0030_scraping__data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraping',
            old_name='_data',
            new_name='data',
        ),
        migrations.AddField(
            model_name='scraping',
            name='url',
            field=models.SlugField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scraping',
            name='name',
            field=models.SlugField(max_length=255),
        ),
    ]
