# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0031_auto_20170326_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='archived_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='archived_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
