# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0032_auto_20170326_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraping',
            name='id',
        ),
        migrations.AlterField(
            model_name='scraping',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mynotes.Note'),
        ),
    ]
