# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-26 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0033_auto_20170326_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('name', models.SlugField(max_length=255)),
                ('url', models.SlugField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField(blank=True, db_column='data')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='archive', serialize=False, to='mynotes.Note')),
            ],
        ),
        migrations.RemoveField(
            model_name='scraping',
            name='note',
        ),
        migrations.DeleteModel(
            name='Scraping',
        ),
    ]
