# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0034_auto_20170326_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='note',
        ),
        migrations.AddField(
            model_name='archive',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
