# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0035_auto_20170329_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='archive',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mynotes.Archive'),
        ),
        migrations.AddField(
            model_name='note',
            name='archive',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mynotes.Archive'),
        ),
    ]
