# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0036_auto_20170329_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnote',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='note',
            name='archive',
        ),
        migrations.AddField(
            model_name='archive',
            name='notes',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='mynotes.Note'),
        ),
    ]
