# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0037_auto_20170329_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='archive_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='archive_id',
            field=models.IntegerField(null=True),
        ),
    ]
