# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0038_auto_20170329_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='notes',
            new_name='note',
        ),
    ]
