# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0039_auto_20170329_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
