# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mynotes', '0040_auto_20170409_1611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'user_cre')]),
        ),
    ]
